### PR TITLE
gulp-sourcemaps: generate .map for .min files

### PR DESCRIPTION
**Pull request by GrumpyPirate**
Implements [gulp-sourcemaps](https://www.npmjs.com/package/gulp-sourcemaps) to generate `.map` files when minifying JS and CSS files.

It's nothing massive, and just allows for easier in-browser debugging when inspecting minified css/js files both in development and production.

### CODE REVIEW

**Comment by MrFirthy** [comment]
I am keeping this one out for now because it doesn't seem to be working fully. The maps are being generated for me locally, but when I attempt to go to a line in the CSS file in the web inspector, it references `styles.css` instead of `styles.min.css` and there is no CSS to be seen in sources tab under `styles.css`

**Comment by ecobbold15** [comment]
Maps now generate with the original content included, which sorts them out.

It's worth noting that when using the inspector to view scripts/style rules, the referenced css/js files will appear as `styles.css`, `main.js` rather than `styles.min.css`, etc. Chrome certainly reads map files by default (as far as I'm aware), but there's a specific option to enable map files in the inspector settings.

Can't speak for other browsers but I assume it works for them in a similar way.

**Comment by MrFirthy** [comment]
It seems that the styleguide still needs to point to the correct `vendor.min.js` file as I am getting console errors when on this branch.

**Comment by ecobbold15** [comment]
Yeah, I cleaned these up in a separate branch - [fix/asset-linking](https://github.com/tangentsnowball/house-styles/tree/fix/asset-linking)

**Comment by MrFirthy** [comment]
If changes from a certain branch would fix issues in these ones, they should be merged together and submitted as one. Although not ideal it means that no pull requests get merged if, by themselves, they cause any errors in the project. Does that make sense?

**Comment by ecobbold15** [comment]
That does makes sense - these however are issues that were already present in `master`; the branches themselves haven't introduced any newer ones. The assets not linking up properly, for example has been in `master` for a while.

I'm also taking the separated branch approach to keep the feature implementation separate - but difficulty arises when I need to build upon functionality I've implemented elsewhere in another branch that hasn't been merged into master yet.

I've been dealing with this by simply merging in that particular branch into the new branch, so I'm unsure how best I should be going about it.

**Comment by MrFirthy** [comment]
It's true that they are in master but this is a because of a previous pull request from when you switched the original bower implementation to the new one and the links weren't updated. Don't worry about though it I'll take care of it.

**Comment by MrFirthy** [comment]
:+1:

**Pull request merged**
